USE YSUNMVMS;

-- 创建用户表，User用方括号是为了防止与SQLServer某些保留字冲突
CREATE TABLE [User] (
    UID NVARCHAR(10) PRIMARY KEY NOT NULL,
    UName NVARCHAR(10) NOT NULL,
    UContact NVARCHAR(20) NOT NULL,
    UVehNum SMALLINT NOT NULL CHECK (UVehNum >= 0),
    UAddress NVARCHAR(30) NOT NULL
);

-- 创建非机动车表
CREATE TABLE Vehicle (
    VID NVARCHAR(10) PRIMARY KEY NOT NULL,
    VType NVARCHAR(10) CHECK (VType IN ('电动车', '自行车', '其它')),
    VProfile NVARCHAR(127),
    VNote NVARCHAR(127),
	[UID] NVARCHAR(10),
    FOREIGN KEY (UID) REFERENCES [User](UID),
);

-- 创建管理员表
CREATE TABLE Admin (
    AID NVARCHAR(10) PRIMARY KEY NOT NULL,
    AName NVARCHAR(10) NOT NULL,
    AContact NVARCHAR(20) NOT NULL
);

-- 创建运维调度员表
CREATE TABLE Maintainer (
    MID NVARCHAR(10) PRIMARY KEY NOT NULL,
    MName NVARCHAR(10) NOT NULL,
    MContact NVARCHAR(20) NOT NULL
);

-- 创建停车位表
CREATE TABLE ParkSpace (
    PSID NVARCHAR(10) PRIMARY KEY NOT NULL,
    PSState NVARCHAR(10) CHECK (PSState IN ('空闲', '占用中', '不可用'))
);

-- 创建充电设施表
CREATE TABLE ChargeDevice (
    CDID NVARCHAR(10) PRIMARY KEY NOT NULL,
    CDState NVARCHAR(10) CHECK (CDState IN ('空闲', '占用中', '不可用'))
);

-- 创建反馈表
CREATE TABLE Feedback (
    FID NVARCHAR(10) PRIMARY KEY NOT NULL,
    FContent NVARCHAR(127) NOT NULL,
    FState NVARCHAR(127) NOT NULL CHECK (FState IN ('待处理', '已处理')),
    UID NVARCHAR(10),
    AID NVARCHAR(10),
    FOREIGN KEY (UID) REFERENCES [User](UID),
    FOREIGN KEY (AID) REFERENCES Admin(AID)
);

-- 创建付款表
CREATE TABLE Payment (
    PID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    PType NVARCHAR(10) CHECK (PType IN ('充电收费', '维修收费')),
    PAmount DECIMAL(10, 2) NOT NULL CHECK (PAmount >= 0),
    PState NVARCHAR(10) CHECK (PState IN ('待付款', '已付款')),
    UID NVARCHAR(10),
    AID NVARCHAR(10),
    FOREIGN KEY (UID) REFERENCES [User](UID),
    FOREIGN KEY (AID) REFERENCES Admin(AID)
);

-- 创建不良行为记录表
CREATE TABLE BadRecord (
    BRID NVARCHAR(10) PRIMARY KEY NOT NULL,
    BRTime SMALLDATETIME NOT NULL,
    BRContent NVARCHAR(127) NOT NULL,
    UID NVARCHAR(10),
    AID NVARCHAR(10),
    FOREIGN KEY (UID) REFERENCES [User](UID),
    FOREIGN KEY (AID) REFERENCES Admin(AID)
);

-- 创建报修表
CREATE TABLE Repair (
    RID NVARCHAR(10) PRIMARY KEY NOT NULL,
    RContent NVARCHAR(127) NOT NULL,
    RState NVARCHAR(10) CHECK (RState IN ('待处理', '处理中', '已完成')),
    UID NVARCHAR(10),
    VID NVARCHAR(10),
    MID NVARCHAR(10),
    FOREIGN KEY (UID) REFERENCES [User](UID),
    FOREIGN KEY (VID) REFERENCES Vehicle(VID),
    FOREIGN KEY (MID) REFERENCES Maintainer(MID)
);

-- 创建停放表
CREATE TABLE VehiclePark (
    VPID NVARCHAR(10) PRIMARY KEY NOT NULL,
    VPStartTime SMALLDATETIME NOT NULL,
    VPEndTime SMALLDATETIME,
    VID NVARCHAR(10),
    PSID NVARCHAR(10),
    CONSTRAINT CHK_VPEndTime CHECK (VPEndTime >= VPStartTime), -- 使用 CONSTRAINT 定义 CHECK 约束
    FOREIGN KEY (VID) REFERENCES Vehicle(VID),
    FOREIGN KEY (PSID) REFERENCES ParkSpace(PSID)
);

-- 创建充电表
CREATE TABLE VehicleCharge (
    VCID NVARCHAR(10) PRIMARY KEY NOT NULL,
    VCStartTime SMALLDATETIME NOT NULL,
    VCEndTime SMALLDATETIME,
    VCState NVARCHAR(10) CHECK (VCState IN ('充电中', '充电结束', '不可用')),
    VID NVARCHAR(10),
    CDID NVARCHAR(10),
	CONSTRAINT CHK_VCEndTime CHECK (VCEndTime >= VCStartTime),
    FOREIGN KEY (VID) REFERENCES Vehicle(VID),
    FOREIGN KEY (CDID) REFERENCES ChargeDevice(CDID)
);

-- 创建停车位维护表
CREATE TABLE ParkSpaceMaintain (
    PSMID NVARCHAR(10) PRIMARY KEY NOT NULL,
    PSMTime SMALLDATETIME NOT NULL,
    PSMRecord NVARCHAR(127) NOT NULL,
    PSID NVARCHAR(10),
    MID NVARCHAR(10),
    FOREIGN KEY (PSID) REFERENCES ParkSpace(PSID),
    FOREIGN KEY (MID) REFERENCES Maintainer(MID)
);

-- 创建充电设施维护表
CREATE TABLE ChargeDeviceMaintain (
    CDMID NVARCHAR(10) PRIMARY KEY NOT NULL,
    CDMTime SMALLDATETIME NOT NULL,
    CDMRecord NVARCHAR(127) NOT NULL,
    CDID NVARCHAR(10),
    MID NVARCHAR(10),
    FOREIGN KEY (CDID) REFERENCES ChargeDevice(CDID),
    FOREIGN KEY (MID) REFERENCES Maintainer(MID)
);

-- 创建调度请求表
CREATE TABLE DispatchRequest (
    DRID NVARCHAR(10) PRIMARY KEY NOT NULL,
    DRContent NVARCHAR(127) NOT NULL,
    DRTime SMALLDATETIME NOT NULL,
    DRState NVARCHAR(10) CHECK (DRState IN ('待处理', '处理中', '处理成功', '处理失败')),
    AID NVARCHAR(10),
    MID NVARCHAR(10),
    FOREIGN KEY (AID) REFERENCES Admin(AID),
    FOREIGN KEY (MID) REFERENCES Maintainer(MID)
);
